SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ALTER TABLE [dbo].[Projects] ADD Start DATETIME NULL;
-- ALTER TABLE [dbo].[Projects] ADD Completion DATETIME NULL;
ALTER TABLE [dbo].[Projects] ADD Status NVARCHAR(10) NOT NULL DEFAULT 'NotStarted';
ALTER TABLE [dbo].[Projects] ADD Priority TINYINT NOT NULL DEFAULT 1;
GO